apiVersion: v1
kind: ConfigMap
apiVersion: v1
metadata:
  name: registry-monitor-hawkular-agent
data:
  hawkular-openshift-agent: |
    endpoints:
    - type: prometheus
      protocol: "http"
      port: 9779
      path: /metrics
      collection_interval_secs: 60
      metrics:
      - name: monitor_failure
        type: counter
      - name: monitor_pull_count
        type: counter
      - name: monitor_push_count
        type: counter
