---
apiVersion: v1
kind: Template
metadata:
  labels:
    provider: fabric8
    group: coreos-registry-monitor
  name: registry-monitor
objects:
- apiVersion: v1
  kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: registry-monitor
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      provider: fabric8
      group: coreos-registry-monitor
    name: ${APP}
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        annotations:
          hawkular-openshift-agent: ${HAWKULAR_AGENT_CONFIGMAP}
        labels:
          provider: fabric8
          group: coreos-registry-monitor
      spec:
        containers:
        - command: ["./monitor","-listen=:9779","-username=$(USERNAME)","-password=$(PASSWORD)","-registry-host=$(REGISTRY_HOST)","-repository=$(REPOSITORY)","-base-layer-id=$(BASE_LAYER)"]
          env:
          - name: UNDER_DOCKER
            value: "true"
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: USERNAME
            valueFrom:
              configMapKeyRef:
                name: registry-monitor-config
                key: username
          - name: PASSWORD
            valueFrom:
              configMapKeyRef:
                name: registry-monitor-config
                key: password
          - name: REGISTRY_HOST
            valueFrom:
              configMapKeyRef:
                name: registry-monitor-config
                key: registry-host
          - name: REPOSITORY
            valueFrom:
              configMapKeyRef:
                name: registry-monitor-config
                key: repository
          - name: BASE_LAYER
            valueFrom:
              configMapKeyRef:
                name: registry-monitor-config
                key: base-layer-id
          image: garethahealy/registry-monitor:1.0
          imagePullPolicy: IfNotPresent
          name: ${APP}
          securityContext:
            privileged: true
          ports:
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-socket
        serviceAccountName: registry-monitor
        volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
    triggers:
    - type: ConfigChange
parameters:
- name: APP
  value: registry-monitor
- name: HAWKULAR_AGENT_CONFIGMAP
  value: registry-monitor-hawkular-agent
